Name: Generate Snake Animation

on:
  schedule:
    # Berjalan otomatis setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Menggunakan versi v4 terbaru (mengatasi peringatan Node.js 20)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Menggunakan versi v3 terbaru untuk generate animasi ular
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Mengunggah hasil ke branch 'output' agar bisa dipanggil sebagai gambar
      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}